### ISSUE TITLE
KPI Tracking 

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-refinement#76]
## Context
As Business Developer I want to track performance indicators to track business growth.
Several datasources need to deliver KPIs and then visualised in a google datastudio dashboard.

## Tasks
-------------------------
- [ ] **Graph business KPIs:** 

1. total amount of organisations  
2. amount of campaigns (total and by status)
3. amount of  identities (total unique identites set on network, amount of sub-attributes like twitter, email etc.)
4. total amount of collectables minted
5. amount of proposals  (total and by status)
6. GAME locked in protocols (total and by orgs, campaigns & proposals)
7. total value locked (all currencies in org-treasuries, campaigns, proposals translated into USD)

-------------------------
- [ ] **Infrastructure tech KPIs each per environment:**

1. uptime frontend 
2.  response times frontend
3. Uptime Graph
4. response times Graph
5. block time chain 
6. block height chain

-------------------------

- [ ] **webtracking:**

1. visits, unique visits
3. create organisation funnel 
4. proposal funnel 
5. campaign funnel 
7. successful joins / join attempts 
8. mine each interaction element (button & link) for tracking
9. track search terms

-------------------------

- [ ] **product team KPIs:**

1. amount of github users
2. github & gitlab commits
3. story points per sprint planned vs. accomplished
4. avg velocity per dev

## Additional Information

- the graph data should be queryable out of google data studio or via a detour as a google sheet
- if possible github data / product team KPIs should be queryable  or via a detout as a google sheet
- webtracking should be a solution which can be setup in a webtracking interface (probably code snippet integration and mining effort, integrable via google data studio)
